diffusion:
  beta_end: 0.7
  beta_start: 0.0001
  c_mask_prob: 0.2
  cfg: true
  channels: 64
  ddim: true
  diffusion_embedding_dim: 128
  is_linear: false
  layers: 4
  multi_source_attn: true
  nheads: 8
  noise_esti: false
  num_steps: 275
  pre_norm: false
  sample_method: quad
  sample_steps: 20
  schedule: quad
  text_gate: mlp
  time_weight: 0.1
  timestep_scale: 1.0
  timestep_scale_learnable: true
model:
  cot_temperature: 0.55
  decomp: false
  featureemb: 16
  guide_w_default: 1.2
  is_unconditional: 0
  llm: bert
  llm_layers: 0
  lookback_len: 36
  multiscale_branch: false
  num_sample_features: 64
  pred_len: 12
  rag_topk: 1
  relative_size_emb_cat: false
  target_strategy: test
  text_len: 36
  timeemb: 128
  timestep_branch: true
  timestep_emb_cat: true
  with_texts: true
train:
  batch_size: 8
  epochs: 1
  itr_per_epoch: 5
  lr: 0.0001
