train:
  epochs: 150
  batch_size: 32
  lr: 0.01
  itr_per_epoch: 100000000.0
  multi_res_horizons:
  - 1
  - 2
  - 4
  - 6
  multi_res_loss_weight: 0.03
  multi_res_use_huber: true
  multi_res_huber_delta: 1.0
  multi_res_dynamic: true
  multi_res_dynamic_by_t: true
  multi_res_dynamic_by_epoch: true
  multi_res_dynamic_by_trend: false
  multi_res_dynamic_min_weight: 0.3
diffusion:
  layers: 6
  channels: 64
  nheads: 8
  diffusion_embedding_dim: 128
  beta_start: 0.0001
  beta_end: 0.4
  num_steps: 400
  schedule: quad
  is_linear: false
  noise_esti: false
  cfg: true
  c_mask_prob: 0.5
  ddim: true
  sample_steps: 90
  sample_method: quad
  pre_norm: false
model:
  is_unconditional: 0
  timeemb: 128
  featureemb: 16
  target_strategy: test
  num_sample_features: 64
  timestep_branch: false
  timestep_emb_cat: true
  with_texts: true
  relative_size_emb_cat: false
  decomp: false
  llm: bert
  llm_layers: 0
  cot_model: ./gpt2-medium
  cot_temperature: 0.4
  cot_max_new_tokens: 64
  guide_w_default: 3.0
  rag_stage1_topk: 9
  rag_stage2_topk: 3
  rag_topk: 3
  use_rag_cot: true
  use_two_stage_rag: true
