# Ablation E0: Baseline
# Dataset: economy seq=36 pred=12

train:
  epochs: 150
  batch_size: 32
  lr: 0.0025
  itr_per_epoch: 100000000.0
  multi_res_loss_weight: 0.0
  use_scale_router: false
diffusion:
  layers: 6
  channels: 64
  nheads: 8
  diffusion_embedding_dim: 128
  beta_start: 0.0001
  beta_end: 0.6
  num_steps: 300
  schedule: quad
  is_linear: false
  noise_esti: false
  cfg: true
  c_mask_prob: 0.05
  ddim: true
  sample_steps: 20
  sample_method: quad
  pre_norm: false
  trend_cfg: false
  trend_cfg_random: false
model:
  is_unconditional: 0
  timeemb: 128
  featureemb: 16
  target_strategy: test
  num_sample_features: 64
  timestep_branch: true
  timestep_emb_cat: true
  with_texts: true
  relative_size_emb_cat: false
  decomp: false
  llm: bert
  llm_layers: 0
  use_rag_cot: false
  use_two_stage_rag: false
